name: Otomatik Görev Zamanlayıcı V2

on:
  workflow_dispatch:
  schedule:
    - cron: '0 3 * * *' # Saati bir saat ileri aldık (03:00 UTC)

jobs:
  run-python-script:
    runs-on: ubuntu-latest
    steps:
      - name: Depoyu Klonla
        uses: actions/checkout@v3

      - name: Python Ortamını Kur
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Gerekli Kütüphaneleri Yükle
        run: |
          python -m pip install --upgrade pip
          pip install gspread oauth2client

      - name: Otomasyon Script'ini Çalıştır
        env:
          GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}
        run: python scheduler.py
