name: Is Takip Robotu ðŸ¤–

on:
  schedule:
    - cron: "*/30 * * * *"  # Her 30 dakikada bir Ã§alÄ±ÅŸ
  workflow_dispatch:        # Ä°stediÄŸinde manuel tetiklemek iÃ§in

jobs:
  calistir:
    runs-on: ubuntu-latest

    steps:
      - name: KodlarÄ± Ã‡ek
        uses: actions/checkout@v3

      - name: Python Kur
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: KÃ¼tÃ¼phaneleri YÃ¼kle
        run: |
          pip install gspread oauth2client requests pandas

      - name: Robotu Ã‡alÄ±ÅŸtÄ±r ðŸš€
        env:
          ID_INSTANCE: ${{ secrets.ID_INSTANCE }}
          API_TOKEN: ${{ secrets.API_TOKEN }}
          GRUP_ID: ${{ secrets.GRUP_ID }}
          GCP_CREDENTIALS: ${{ secrets.GCP_CREDENTIALS }}
        run: python hatirlatici.py
